### ISSUE TITLE
Dashboard keeps crashing

### ISSUE THREAD

**Issue by nickzhums** [microsoft/vscode-spring-boot-dashboard#183]
This problem might be caused by upstream tools but since I am using the dashboard so I will log it here first.. Here's the log

Activating 'vscode-spring-boot' extension
"spring-boot.ls.java.home" setting not specified or empty value
Found java executable: c:\Users\littl\.vscode\extensions\redhat.java-1.7.0-win32-x64\jre\17.0.3-win32-x86_64\bin\java.exe
isJavaEightOrHigher => true
Redirecting server logs to /dev/null
Disabling server log output. No more output will be sent after this.
[Info  - 4:41:23 PM] Connection to server got closed. Server will restart.
[Error - 4:41:23 PM] Request textDocument/codeLens failed.
Error: Connection got disposed.
    at Object.dispose (c:\Users\littl\.vscode\extensions\pivotal.vscode-spring-boot-1.33.0\node_modules\vscode-jsonrpc\lib\common\connection.js:1044:27)
    at Object.dispose (c:\Users\littl\.vscode\extensions\pivotal.vscode-spring-boot-1.33.0\node_modules\vscode-languageclient\lib\common\client.js:73:35)
    at LanguageClient.handleConnectionClosed (c:\Users\littl\.vscode\extensions\pivotal.vscode-spring-boot-1.33.0\node_modules\vscode-languageclient\lib\common\client.js:2424:42)
    at LanguageClient.handleConnectionClosed (c:\Users\littl\.vscode\extensions\pivotal.vscode-spring-boot-1.33.0\node_modules\vscode-languageclient\lib\node\main.js:155:15)
    at closeHandler (c:\Users\littl\.vscode\extensions\pivotal.vscode-spring-boot-1.33.0\node_modules\vscode-languageclient\lib\common\client.js:2411:18)
    at CallbackList.invoke (c:\Users\littl\.vscode\extensions\pivotal.vscode-spring-boot-1.33.0\node_modules\vscode-jsonrpc\lib\common\events.js:55:39)
    at Emitter.fire (c:\Users\littl\.vscode\extensions\pivotal.vscode-spring-boot-1.33.0\node_modules\vscode-jsonrpc\lib\common\events.js:117:36)
    at closeHandler (c:\Users\littl\.vscode\extensions\pivotal.vscode-spring-boot-1.33.0\node_modules\vscode-jsonrpc\lib\common\connection.js:256:26)
    at CallbackList.invoke (c:\Users\littl\.vscode\extensions\pivotal.vscode-spring-boot-1.33.0\node_modules\vscode-jsonrpc\lib\common\events.js:55:39)
    at Emitter.fire (c:\Users\littl\.vscode\extensions\pivotal.vscode-spring-boot-1.33.0\node_modules\vscode-jsonrpc\lib\common\events.js:117:36)
    at StreamMessageReader.fireClose (c:\Users\littl\.vscode\extensions\pivotal.vscode-spring-boot-1.33.0\node_modules\vscode-jsonrpc\lib\common\messageReader.js:40:27)
    at Socket.<anonymous> (c:\Users\littl\.vscode\extensions\pivotal.vscode-spring-boot-1.33.0\node_modules\vscode-jsonrpc\lib\common\messageReader.js:125:42)
    at Socket.emit (node:events:402:35)
    at Pipe.<anonymous> (node:net:687:12)

Disabling server log output. No more output will be sent after this.
[Info  - 4:42:35 PM] Connection to server got closed. Server will restart.
Disabling server log output. No more output will be sent after this.
[Info  - 4:43:17 PM] Connection to server got closed. Server will restart.
Disabling server log output. No more output will be sent after this.
[Info  - 4:44:00 PM] Connection to server got closed. Server will restart.
Disabling server log output. No more output will be sent after this.
[Info  - 4:44:42 PM] Connection to server got closed. Server will restart.
Disabling server log output. No more output will be sent after this.
[Error - 4:45:24 PM] Connection to server got closed. Server will not be restarted.

**Comment by Eskibear** [comment]
Yes, it should be related to upstream vscode-spring-tools. STS-LS crashed somehow. Check if you have any strange spring-related settings first?

**Comment by nickzhums** [comment]
Since it no longer happens, i'm closing this issue
