### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'client')

### ISSUE THREAD

**Issue by CsCherrYY** [microsoft/vscode-spring-boot-dashboard#195]
steps to reproduce:

1. git clone https://github.com/spring-projects/spring-petclinic
2. open in VS Code
3. open developer tools
4. can see the error:
> TypeError: Cannot read properties of undefined (reading 'client')
	at c:\Users\chenshi\.vscode\extensions\vscjava.vscode-spring-boot-dashboard-0.6.0\out\models\stsApi.js:154:44
	at Generator.next (<anonymous>)
	at c:\Users\chenshi\.vscode\extensions\vscjava.vscode-spring-boot-dashboard-0.6.0\out\models\stsApi.js:10:71
	at new Promise (<anonymous>)
	at __awaiter (c:\Users\chenshi\.vscode\extensions\vscjava.vscode-spring-boot-dashboard-0.6.0\out\models\stsApi.js:6:12)
	at requestWorkspaceSymbols (c:\Users\chenshi\.vscode\extensions\vscjava.vscode-spring-boot-dashboard-0.6.0\out\models\stsApi.js:153:12)
	at c:\Users\chenshi\.vscode\extensions\vscjava.vscode-spring-boot-dashboard-0.6.0\out\models\symbols.js:30:72
	at Generator.next (<anonymous>)
	at c:\Users\chenshi\.vscode\extensions\vscjava.vscode-spring-boot-dashboard-0.6.0\out\models\symbols.js:10:71
	at new Promise (<anonymous>)

**Comment by Eskibear** [comment]
looks like `stsApi` is undefined, will investigate whether there's somewhere calling stsApi.client before sts-vscode is activated.
