### ISSUE TITLE
ClassNotFoundException during startup of application using dashboard although it is working when using "mvn spring-boot:run"

### ISSUE THREAD

**Issue by apupier** [Microsoft/vscode-spring-boot-dashboard#52]
using https://github.com/jboss-fuse/fuse-springboot-circuit-breaker-booster

- change server.port in greetings-service/src/main/resources/application.properties to avoid conflict.
- in dashboard view, right-click "name-service" then run
- in dashboard view, right-click "greeting-service" then run
--> 
<details>
<summary> [ click to show detailed logs ] </summary>

```
:: Spring Boot ::       (v1.5.13.RELEASE)



2018-11-12 16:20:59.947  INFO 69708 --- [           main] com.redhat.fuse.boosters.cb.Application  : Starting Application on DESKTOP-9NT300B with PID 69708 (C:\ws\workingDirectoryForTest\test-circuitBreaker-withFixedSpringbootdashboard\fuse-springboot-circuit-breaker-booster\greetings-service\target\classes started by Aurelien Pupier in C:\ws\workingDirectoryForTest\test-circuitBreaker-withFixedSpringbootdashboard\fuse-springboot-circuit-breaker-booster)

2018-11-12 16:20:59.951  INFO 69708 --- [           main] com.redhat.fuse.boosters.cb.Application  : No active profile set, falling back to default profiles: default

2018-11-12 16:21:00.013  INFO 69708 --- [           main] ationConfigEmbeddedWebApplicationContext : Refreshing org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@7c0c77c7: startup date [Mon Nov 12 16:21:00 CET 2018]; root of context hierarchy

2018-11-12 16:21:01.079  INFO 69708 --- [           main] o.s.b.f.s.DefaultListableBeanFactory     : Overriding bean definition for bean 'servletRegistrationBean' with a different definition: replacing [Root bean: class [null]; scope=; abstract=false; lazyInit=false; autowireMode=3; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=org.apache.camel.component.hystrix.springboot.HystrixMappingAutoConfiguration; factoryMethodName=servletRegistrationBean; initMethodName=null; destroyMethodName=(inferred); defined in class path resource [org/apache/camel/component/hystrix/springboot/HystrixMappingAutoConfiguration.class]] with [Root bean: class [null]; scope=; abstract=false; lazyInit=false; autowireMode=3; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=org.apache.camel.component.servlet.springboot.ServletMappingAutoConfiguration; factoryMethodName=servletRegistrationBean; initMethodName=null; destroyMethodName=(inferred); defined in class path resource [org/apache/camel/component/servlet/springboot/ServletMappingAutoConfiguration.class]]

2018-11-12 16:21:02.442  INFO 69708 --- [           main] org.xnio                                 : XNIO version 3.3.8.Final

2018-11-12 16:21:02.461  INFO 69708 --- [           main] org.xnio.nio                             : XNIO NIO Implementation Version 3.3.8.Final

2018-11-12 16:21:02.517  WARN 69708 --- [           main] io.undertow.websockets.jsr               : UT026009: XNIO worker was not set on WebSocketDeploymentInfo, the default worker will be used

2018-11-12 16:21:02.517  WARN 69708 --- [           main] io.undertow.websockets.jsr               : UT026010: Buffer pool was not set on WebSocketDeploymentInfo, the default pool will be used

2018-11-12 16:21:02.548  INFO 69708 --- [           main] io.undertow.servlet                      : Initializing Spring embedded WebApplicationContext

2018-11-12 16:21:02.549  INFO 69708 --- [           main] o.s.web.context.ContextLoader            : Root WebApplicationContext: initialization completed in 2538 ms

2018-11-12 16:21:02.582  WARN 69708 --- [           main] ationConfigEmbeddedWebApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.context.ApplicationContextException: Unable to start embedded container; nested exception is java.lang.RuntimeException: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'hystrixEventStreamServlet' defined in com.redhat.fuse.boosters.cb.Application: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.boot.web.servlet.ServletRegistrationBean]: Factory method 'servletRegistrationBean' threw exception; nested exception is java.lang.NoClassDefFoundError: org/apache/commons/lang/text/StrLookup

2018-11-12 16:21:02.600  INFO 69708 --- [           main] utoConfigurationReportLoggingInitializer : 



Error starting ApplicationContext. To display the auto-configuration report re-run your application with 'debug' enabled.

2018-11-12 16:21:02.615 ERROR 69708 --- [           main] o.s.boot.SpringApplication               : Application startup failed



org.springframework.context.ApplicationContextException: Unable to start embedded container; nested exception is java.lang.RuntimeException: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'hystrixEventStreamServlet' defined in com.redhat.fuse.boosters.cb.Application: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.boot.web.servlet.ServletRegistrationBean]: Factory method 'servletRegistrationBean' threw exception; nested exception is java.lang.NoClassDefFoundError: org/apache/commons/lang/text/StrLookup

	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.onRefresh(EmbeddedWebApplicationContext.java:137) ~[spring-boot-1.5.13.RELEASE.jar:1.5.13.RELEASE]

	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:537) ~[spring-context-4.3.17.RELEASE.jar:4.3.17.RELEASE]

	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122) ~[spring-boot-1.5.13.RELEASE.jar:1.5.13.RELEASE]

	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:693) [spring-boot-1.5.13.RELEASE.jar:1.5.13.RELEASE]

	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:360) [spring-boot-1.5.13.RELEASE.jar:1.5.13.RELEASE]

	at org.springframework.boot.SpringApplication.run(SpringApplication.java:303) [spring-boot-1.5.13.RELEASE.jar:1.5.13.RELEASE]

	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1118) [spring-boot-1.5.13.RELEASE.jar:1.5.13.RELEASE]

	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1107) [spring-boot-1.5.13.RELEASE.jar:1.5.13.RELEASE]

	at com.redhat.fuse.boosters.cb.Application.main(Application.java:21) [classes/:na]

Caused by: java.lang.RuntimeException: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'hystrixEventStreamServlet' defined in com.redhat.fuse.boosters.cb.Application: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.boot.web.servlet.ServletRegistrationBean]: Factory method 'servletRegistrationBean' threw exception; nested exception is java.lang.NoClassDefFoundError: org/apache/commons/lang/text/StrLookup

	at io.undertow.servlet.core.DeploymentManagerImpl.deploy(DeploymentManagerImpl.java:241) ~[undertow-servlet-1.4.25.Final.jar:1.4.25.Final]

	at org.springframework.boot.context.embedded.undertow.UndertowEmbeddedServletContainerFactory.createDeploymentManager(UndertowEmbeddedServletContainerFactory.java:412) ~[spring-boot-1.5.13.RELEASE.jar:1.5.13.RELEASE]

	at org.springframework.boot.context.embedded.undertow.UndertowEmbeddedServletContainerFactory.getEmbeddedServletContainer(UndertowEmbeddedServletContainerFactory.java:234) ~[spring-boot-1.5.13.RELEASE.jar:1.5.13.RELEASE]

	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.createEmbeddedServletContainer(EmbeddedWebApplicationContext.java:164) ~[spring-boot-1.5.13.RELEASE.jar:1.5.13.RELEASE]

	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.onRefresh(EmbeddedWebApplicationContext.java:134) ~[spring-boot-1.5.13.RELEASE.jar:1.5.13.RELEASE]

	... 8 common frames omitted

Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'hystrixEventStreamServlet' defined in com.redhat.fuse.boosters.cb.Application: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.boot.web.servlet.ServletRegistrationBean]: Factory method 'servletRegistrationBean' threw exception; nested exception is java.lang.NoClassDefFoundError: org/apache/commons/lang/text/StrLookup

	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:599) ~[spring-beans-4.3.17.RELEASE.jar:4.3.17.RELEASE]

	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1181) ~[spring-beans-4.3.17.RELEASE.jar:4.3.17.RELEASE]

	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1075) ~[spring-beans-4.3.17.RELEASE.jar:4.3.17.RELEASE]

	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:513) ~[spring-beans-4.3.17.RELEASE.jar:4.3.17.RELEASE]

	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483) ~[spring-beans-4.3.17.RELEASE.jar:4.3.17.RELEASE]

	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:312) ~[spring-beans-4.3.17.RELEASE.jar:4.3.17.RELEASE]

	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230) ~[spring-beans-4.3.17.RELEASE.jar:4.3.17.RELEASE]

	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:308) ~[spring-beans-4.3.17.RELEASE.jar:4.3.17.RELEASE]

	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202) ~[spring-beans-4.3.17.RELEASE.jar:4.3.17.RELEASE]

	at org.springframework.boot.web.servlet.ServletContextInitializerBeans.getOrderedBeansOfType(ServletContextInitializerBeans.java:234) ~[spring-boot-1.5.13.RELEASE.jar:1.5.13.RELEASE]

	at org.springframework.boot.web.servlet.ServletContextInitializerBeans.getOrderedBeansOfType(ServletContextInitializerBeans.java:215) ~[spring-boot-1.5.13.RELEASE.jar:1.5.13.RELEASE]

	at org.springframework.boot.web.servlet.ServletContextInitializerBeans.addServletContextInitializerBeans(ServletContextInitializerBeans.java:91) ~[spring-boot-1.5.13.RELEASE.jar:1.5.13.RELEASE]

	at org.springframework.boot.web.servlet.ServletContextInitializerBeans.<init>(ServletContextInitializerBeans.java:79) ~[spring-boot-1.5.13.RELEASE.jar:1.5.13.RELEASE]

	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.getServletContextInitializerBeans(EmbeddedWebApplicationContext.java:241) ~[spring-boot-1.5.13.RELEASE.jar:1.5.13.RELEASE]

	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.selfInitialize(EmbeddedWebApplicationContext.java:228) ~[spring-boot-1.5.13.RELEASE.jar:1.5.13.RELEASE]

	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.access$000(EmbeddedWebApplicationContext.java:89) ~[spring-boot-1.5.13.RELEASE.jar:1.5.13.RELEASE]

	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext$1.onStartup(EmbeddedWebApplicationContext.java:213) ~[spring-boot-1.5.13.RELEASE.jar:1.5.13.RELEASE]

	at org.springframework.boot.context.embedded.undertow.UndertowEmbeddedServletContainerFactory$Initializer.onStartup(UndertowEmbeddedServletContainerFactory.java:723) ~[spring-boot-1.5.13.RELEASE.jar:1.5.13.RELEASE]

	at io.undertow.servlet.core.DeploymentManagerImpl$1.call(DeploymentManagerImpl.java:192) ~[undertow-servlet-1.4.25.Final.jar:1.4.25.Final]

	at io.undertow.servlet.core.DeploymentManagerImpl$1.call(DeploymentManagerImpl.java:174) ~[undertow-servlet-1.4.25.Final.jar:1.4.25.Final]

	at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:42) ~[undertow-servlet-1.4.25.Final.jar:1.4.25.Final]

	at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43) ~[undertow-servlet-1.4.25.Final.jar:1.4.25.Final]

	at io.undertow.servlet.core.DeploymentManagerImpl.deploy(DeploymentManagerImpl.java:239) ~[undertow-servlet-1.4.25.Final.jar:1.4.25.Final]

	... 12 common frames omitted

Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.boot.web.servlet.ServletRegistrationBean]: Factory method 'servletRegistrationBean' threw exception; nested exception is java.lang.NoClassDefFoundError: org/apache/commons/lang/text/StrLookup

	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:189) ~[spring-beans-4.3.17.RELEASE.jar:4.3.17.RELEASE]

	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:588) ~[spring-beans-4.3.17.RELEASE.jar:4.3.17.RELEASE]

	... 34 common frames omitted

Caused by: java.lang.NoClassDefFoundError: org/apache/commons/lang/text/StrLookup

	at com.netflix.config.ConfigurationManager.getConfigInstance(ConfigurationManager.java:125) ~[archaius-core-0.4.1.jar:na]

	at com.netflix.config.DynamicPropertyFactory.getInstance(DynamicPropertyFactory.java:263) ~[archaius-core-0.4.1.jar:na]

	at com.netflix.hystrix.contrib.metrics.eventstream.HystrixMetricsStreamServlet.<clinit>(HystrixMetricsStreamServlet.java:55) ~[hystrix-metrics-event-stream-1.5.12.jar:1.5.12]

	at com.redhat.fuse.boosters.cb.Application.servletRegistrationBean(Application.java:26) [classes/:na]

	at com.redhat.fuse.boosters.cb.Application$$EnhancerBySpringCGLIB$$e4e25142.CGLIB$servletRegistrationBean$0(<generated>) ~[classes/:na]

	at com.redhat.fuse.boosters.cb.Application$$EnhancerBySpringCGLIB$$e4e25142$$FastClassBySpringCGLIB$$d5d9ee19.invoke(<generated>) ~[classes/:na]

	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228) ~[spring-core-4.3.17.RELEASE.jar:4.3.17.RELEASE]

	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:358) ~[spring-context-4.3.17.RELEASE.jar:4.3.17.RELEASE]

	at com.redhat.fuse.boosters.cb.Application$$EnhancerBySpringCGLIB$$e4e25142.servletRegistrationBean(<generated>) ~[classes/:na]

	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_171]

	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_171]

	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_171]

	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_171]

	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:162) ~[spring-beans-4.3.17.RELEASE.jar:4.3.17.RELEASE]

	... 35 common frames omitted

Caused by: java.lang.ClassNotFoundException: org.apache.commons.lang.text.StrLookup

	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[na:1.8.0_171]

	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[na:1.8.0_171]

	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349) ~[na:1.8.0_171]

	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_171]

	... 49 common frames omitted
```
</details>
if _mvn spring-boot:run_ is used from the terminal of VS Code, it is working fine

**Comment by Eskibear** [comment]
I cannot reproduce it, it works well in my machine. Can you provide more details to stably reproduce it?

FYI I changed port of name-service to 8081 to get it work, otherwise greeting-service cannot talk to name-service (but both projects are up and working well). 

#### Attaching my conf
* greeting service
```
server.port=8080

nameService.host=localhost
nameService.port=8081

# configure hystrix
...
```

* name service
```
server.port=8081   # <=== I change the port here 

# disable all management enpoints except health
...
```

![image](https://user-images.githubusercontent.com/2351748/48386721-e6693800-e72d-11e8-8216-9437cab1e8bf.png)

**Comment by apupier** [comment]
@Eskibear thanks for tried to reproduce

I recorded a screencast to show how I reproduce it https://drive.google.com/open?id=1CKMh0PxVPdDAY2bR8gKMC5X-DdGljkQd
I always reproduce it, I think it is now the 10th times that I've done it and I hit the issue 100% of time.

I don't know how I could investigate. I don't understand why it behaves differently from command-line and from UI.

I have the latest version installed
![image](https://user-images.githubusercontent.com/1105127/48400622-2b3da080-e727-11e8-9e78-2faa1d0536fe.png)

I'm on Windows 10, can it be specific to Windows? @Eskibear  On which OS have you tried?

**Comment by Eskibear** [comment]
@apupier I'm on Windows 10. 

Let's dig more into it. 
1. To make sure we have the same source code.  I'm using the latest master bits of your repo (commit  4574fd1)
2. Let's see if it's problem of the dashboard.
  i) Start your services in "Debug" panel.  If the problem exists, it's nothing to do with the boot dashboard.
![image](https://user-images.githubusercontent.com/2351748/48405666-ae81e500-e76d-11e8-8301-b692bc43ca9a.png)

3. Further investigation to see if it's language server issues. (if needed)
  i) Following the screenshot to update project configuration, and see if the issue is gone. 
![image](https://user-images.githubusercontent.com/2351748/48405648-a0cc5f80-e76d-11e8-8bc2-4a6ce1623ce9.png)

**Comment by apupier** [comment]
> 2\. Let's see if it's problem of the dashboard.
>     i) Start your services in "Debug" panel.  If the problem exists, it's nothing to do with the boot dashboard.

ok, I reproduce also using Debug.
So not a Dashboard issue, where can I ask for help then?

**Comment by Eskibear** [comment]
@apupier Yes, it depends on the language server extension. As I mentioned, did you try the third step? right click on pom.xml for greeting-service, and update the project configuration. Sometimes the language server doesn't sync well with your projects, so I guess it's likely to resolve your issue.
> Further investigation to see if it's language server issues. (if needed)
> i) Following the screenshot to update project configuration, and see if the issue is gone

**Comment by Eskibear** [comment]
@testforstephen The log is collapsed above. Do you know if it's the debugger issue or language server issue?

**Comment by Eskibear** [comment]
We can reproduce the issue with Java 10+, and it works well in Java 8. So I guess you have set `java.home` to JDK10+ in VSCode (language server honor this one), and the env `JAVA_HOME` is JDK8 (mvn honor this one)

@apupier What's your Java version?
* Value of JAVA_HOME (if exists)
* Value of `java.home` in your VSCode settings (if set)

**Comment by apupier** [comment]
![image](https://user-images.githubusercontent.com/1105127/48470959-1f1f1500-e7f3-11e8-9b55-1ae458228ac6.png)

![image](https://user-images.githubusercontent.com/1105127/48470885-fa2aa200-e7f2-11e8-8c8d-2eed5e39cf10.png)

I have Java 10 and java 11 jvm on my machine but I don't understand why they would have been taken :(

**Comment by Eskibear** [comment]
If you manually set `java.home` to the home of jdk1.8, can it work? If so, I think we should open an issue in the related repo to figure out why it takes the wrong JDK.

**Comment by apupier** [comment]
I tried with setting the java.home value, unfortunately, there is still the same error.

But based on initial stacktrace, it seems like the correct jvm was used:

at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_171]

I think the 1.8.0_171 corresponds to the JVM version.

**Comment by apupier** [comment]
from command line, with mvn depdency:tree, i can see the commons-lang dependency well marked:

```
+- org.apache.camel:camel-hystrix-starter:jar:2.21.2:compile
[INFO] |  \- org.apache.camel:camel-hystrix:jar:2.21.2:compile
[INFO] |     +- com.netflix.hystrix:hystrix-core:jar:1.5.12:compile
[INFO] |     |  +- com.netflix.archaius:archaius-core:jar:0.4.1:compile
[INFO] |     |  |  \- commons-configuration:commons-configuration:jar:1.8:compile
[INFO] |     |  |     \- commons-lang:commons-lang:jar:2.6:compile
```
I'm wondering if there is a way to see the classpath used when building/launching the program in VS Code? (in Eclipse IDE, for instance it is listed in the project explorer)

**Comment by apupier** [comment]
> wouhou I reproduced the issue from command-line when using Maven 3.5.3 instead of 3.3.9!
> 
> so seems related to Maven version used. I think that Vs Code is relying on Eclipse JDT which is embedding a 3.5.x in latest versions as far as I know.
> 
> so nothing related to the dashboard. Seems an issue of the project or of Maven 3.5.x or of Spring-boot itself, isn't it?

but it wouldn't explain why it is working for you except when using java 10

**Comment by apupier** [comment]
I want to cry...

there was an artefact corrupted commons-configuration in my .m2

I don't understand why it was working from command-line with Maven 3..3.9 only. Or it was in a format understandable only with Maven 3.3.9?

Anyway, I really thank you @Eskibear and @testforstephen for your precious help!
